server.port=8080
spring.application.name=2026-rest-foods-backend--team-2-
app.cors.allowed-origin-patterns=http://localhost:*,http://127.0.0.1:*
spring.datasource.url=jdbc:postgresql://localhost:5434/restaurant
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
